/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pet;

import Classes.ClientesDao;
import Classes.EnderecoDao;
import Modelo.Clientes;
import Modelo.Endereco;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas.delGiudce
 */
public class novoCliente extends javax.swing.JFrame {

    private int id = -1;
    
    
    public novoCliente() {
        initComponents();
    }
    
    public novoCliente(int id) {
        this();
        this.id = id;
        this.setTitle("Alterar Contato");
        
        try{
            
            ClientesDao consultar = new ClientesDao();        
            Clientes cliente = consultar.procurar(id);
            tf_nome.setText(cliente.getNome());
            tf_sobrenome.setText(cliente.getSobrenome());
            tf_cpf.setText(cliente.getCpf());
            tf_telefone.setText(cliente.getTelefone());
            //JOptionPane.showMessageDialog(null, cliente.getIdEndereco());            
            
            EnderecoDao consultarEndereco = new EnderecoDao();        
            Endereco endereco = consultarEndereco.procurar(cliente.getIdEndereco());
            tf_rua.setText(endereco.getRua());
            tf_numero.setText(endereco.getNumero());
            tf_bairro.setText(endereco.getBairro());
            tf_cidade.setText(endereco.getCidade());        
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, 
                    "Opss! Ocorreu um erro: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btn_animal = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tf_telefone = new javax.swing.JTextField();
        tf_nome = new javax.swing.JTextField();
        tf_sobrenome = new javax.swing.JTextField();
        tf_cpf = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_rua = new javax.swing.JTextField();
        tf_numero = new javax.swing.JTextField();
        tf_bairro = new javax.swing.JTextField();
        tf_cidade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jPanel1.setLayout(null);

        jPanel3.setLayout(null);

        btn_animal.setBackground(new java.awt.Color(0, 102, 204));
        btn_animal.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        btn_animal.setForeground(new java.awt.Color(255, 255, 255));
        btn_animal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ico_pata.png"))); // NOI18N
        btn_animal.setText("Animais");
        btn_animal.setToolTipText("Adicionar animais");
        btn_animal.setBorder(null);
        btn_animal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_animal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_animalMouseClicked(evt);
            }
        });
        btn_animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_animalActionPerformed(evt);
            }
        });
        jPanel3.add(btn_animal);
        btn_animal.setBounds(420, 20, 120, 50);

        btn_salvar.setBackground(new java.awt.Color(0, 102, 204));
        btn_salvar.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        btn_salvar.setForeground(new java.awt.Color(255, 255, 255));
        btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ico_salvar.png"))); // NOI18N
        btn_salvar.setText("Salvar");
        btn_salvar.setToolTipText("Salvar dados");
        btn_salvar.setBorder(null);
        btn_salvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_salvar);
        btn_salvar.setBounds(550, 20, 110, 50);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 320, 730, 80);

        jPanel4.setBackground(new java.awt.Color(0, 102, 204));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 280));
        jPanel4.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ende");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(90, 10, 90, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Número:");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(50, 130, 100, 20);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Rua:");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(50, 70, 60, 20);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Bairro:");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(50, 190, 80, 20);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Cidade:");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(50, 250, 100, 20);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(360, 0, 180, 320);

        jPanel5.setBackground(new java.awt.Color(0, 102, 204));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 380));
        jPanel5.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dados");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(70, 10, 110, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefone:");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(40, 250, 110, 20);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nome:");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(40, 70, 80, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sobrenome:");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(40, 130, 139, 20);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CPF:");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(40, 190, 100, 20);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 0, 180, 320);

        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Pessoais");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 10, 160, 30);

        tf_telefone.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_telefone.setForeground(new java.awt.Color(0, 102, 204));
        tf_telefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_telefoneMouseClicked(evt);
            }
        });
        jPanel2.add(tf_telefone);
        tf_telefone.setBounds(20, 250, 140, 21);

        tf_nome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_nome.setForeground(new java.awt.Color(0, 102, 204));
        tf_nome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_nomeMouseClicked(evt);
            }
        });
        tf_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nomeActionPerformed(evt);
            }
        });
        jPanel2.add(tf_nome);
        tf_nome.setBounds(20, 70, 140, 21);

        tf_sobrenome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_sobrenome.setForeground(new java.awt.Color(0, 102, 204));
        tf_sobrenome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_sobrenomeMouseClicked(evt);
            }
        });
        jPanel2.add(tf_sobrenome);
        tf_sobrenome.setBounds(20, 130, 140, 21);

        tf_cpf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_cpf.setForeground(new java.awt.Color(0, 102, 204));
        tf_cpf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_cpfMouseClicked(evt);
            }
        });
        jPanel2.add(tf_cpf);
        tf_cpf.setBounds(20, 190, 140, 21);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(180, 0, 180, 320);

        jPanel7.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.add(jPanel6);
        jPanel6.setBounds(160, 0, 30, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("reço");
        jPanel7.add(jLabel5);
        jLabel5.setBounds(0, 0, 80, 50);

        tf_rua.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_rua.setForeground(new java.awt.Color(0, 102, 204));
        tf_rua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_ruaMouseClicked(evt);
            }
        });
        jPanel7.add(tf_rua);
        tf_rua.setBounds(20, 70, 140, 21);

        tf_numero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_numero.setForeground(new java.awt.Color(0, 102, 204));
        tf_numero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_numeroMouseClicked(evt);
            }
        });
        jPanel7.add(tf_numero);
        tf_numero.setBounds(20, 130, 140, 21);

        tf_bairro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_bairro.setForeground(new java.awt.Color(0, 102, 204));
        tf_bairro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_bairroMouseClicked(evt);
            }
        });
        jPanel7.add(tf_bairro);
        tf_bairro.setBounds(20, 190, 140, 21);

        tf_cidade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_cidade.setForeground(new java.awt.Color(0, 102, 204));
        tf_cidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_cidadeMouseClicked(evt);
            }
        });
        jPanel7.add(tf_cidade);
        tf_cidade.setBounds(20, 250, 140, 21);

        jPanel1.add(jPanel7);
        jPanel7.setBounds(540, 0, 190, 320);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(728, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void tf_telefoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_telefoneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_telefoneMouseClicked

    private void tf_nomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_nomeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nomeMouseClicked

    private void tf_sobrenomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_sobrenomeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_sobrenomeMouseClicked

    private void tf_cpfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_cpfMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cpfMouseClicked

    private void tf_ruaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_ruaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ruaMouseClicked

    private void tf_numeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_numeroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_numeroMouseClicked

    private void tf_bairroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_bairroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_bairroMouseClicked

    private void tf_cidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_cidadeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cidadeMouseClicked

    private void btn_animalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_animalMouseClicked
        
    }//GEN-LAST:event_btn_animalMouseClicked

    private void tf_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nomeActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        
        Clientes cliente = new Clientes();
        Endereco endereco = new Endereco();
        
        if (id == -1){
        try {            
            
            endereco.setRua(tf_rua.getText());
            endereco.setNumero(tf_numero.getText());
            endereco.setBairro(tf_bairro.getText());
            endereco.setCidade(tf_cidade.getText());

            EnderecoDao cadastrarEndereco = new EnderecoDao();
            endereco = cadastrarEndereco.inserir(endereco);

            JOptionPane.showMessageDialog(this, endereco.getId());            
            
            //JOptionPane.showMessageDialog(this, "Endereço Cadastrado    TIRAR");            
            
            cliente.setNome(tf_nome.getText());
            cliente.setCpf(tf_cpf.getText());
            cliente.setSobrenome(tf_sobrenome.getText());
            cliente.setTelefone(tf_telefone.getText());
            cliente.setIdEndereco(endereco.getId());

            ClientesDao cadastrar = new ClientesDao();
            cliente = cadastrar.inserir(cliente);

            JOptionPane.showMessageDialog(this, "Registro cadastrado");
            dispose();   
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao inserir registro: \n"
                    + e.getMessage());
        }
        }
        
        
        else{
            try {
                ClientesDao clienteProcurar = new ClientesDao();
                Clientes idEndereco = clienteProcurar.procurar(id);
                endereco.setId(idEndereco.getIdEndereco());
                endereco.setRua(tf_rua.getText());
                endereco.setNumero(tf_numero.getText());
                endereco.setBairro(tf_bairro.getText());
                endereco.setCidade(tf_cidade.getText());
                EnderecoDao enderecoAlterar = new EnderecoDao();
                endereco = enderecoAlterar.alterar(endereco);
                //JOptionPane.showMessageDialog(this, "Endereco alterado!");
                
                cliente.setId(id);
                cliente.setNome(tf_nome.getText());
                cliente.setCpf(tf_cpf.getText());
                cliente.setSobrenome(tf_sobrenome.getText());
                cliente.setTelefone(tf_telefone.getText());
                cliente.setIdEndereco(endereco.getId());
                
                ClientesDao clienteAlterar = new ClientesDao();
                cliente = clienteAlterar.alterar(cliente);
                JOptionPane.showMessageDialog(this, "Registro alterado!");
                dispose();
                
            }
            
            catch(Exception e) {
                JOptionPane.showMessageDialog(this, "Erro na alteração do registro:\n"
                        + e.getMessage());
            }
        }
        
        
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_animalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_animalActionPerformed
        
        animal novoanimalFrame = new animal();
        novoanimalFrame.setVisible(true);
        
    }//GEN-LAST:event_btn_animalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(novoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(novoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(novoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(novoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new novoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_animal;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField tf_bairro;
    private javax.swing.JTextField tf_cidade;
    private javax.swing.JTextField tf_cpf;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_numero;
    private javax.swing.JTextField tf_rua;
    private javax.swing.JTextField tf_sobrenome;
    private javax.swing.JTextField tf_telefone;
    // End of variables declaration//GEN-END:variables
}
